/* resource file indicies for MSECHO */

#define ECHO     0	/* form/dialog */
#define OFF      4	/* BOX in tree ECHO */
#define INFOS    5	/* BOXTEXT in tree ECHO */
#define ON       6	/* BOX in tree ECHO */
#define DELAY    8	/* TEXT in tree ECHO */
#define DPLUS    9	/* BOXTEXT in tree ECHO */
#define DMOINS   10	/* BOXTEXT in tree ECHO */
#define AMORT    14	/* TEXT in tree ECHO */
#define APLUS    15	/* BOXTEXT in tree ECHO */
#define AMOINS   16	/* BOXTEXT in tree ECHO */

#define MENU     1	/* menu tree */
#define MESSAGE  7	/* STRING in tree MENU */

#define INFORME  2	/* form/dialog */
#define VERSION  3	/* TEXT in tree INFORME */
#define INFOUT   36	/* BUTTON in tree INFORME */
#define VAPPL    39	/* TEXT in tree INFORME */

