#define ERR_NOMEMORY    0
#define ERR_NOOPEN      1
#define ERR_NOINFO      2
#define ERR_NOHELP      3
#define ERR_HELPTRAS    4
#define ERR_HELPPRIN    5
#define ERR_HELPDISK    6
#define ERR_HELPEDIT    7
#define ERR_HELPCLIP    8
#define ERR_HELPIMAG    9
#define ERR_HELPMETA   10
#define ERR_INFTRASH   11
#define ERR_INFPRINT   12
#define ERR_INFDISK    13
#define ERR_INFEDIT    14
#define ERR_INFCLIP    15
#define ERR_INFIMAGE   16
#define ERR_TEXT       17
#define ERR_FOPEN      18
#define ERR_FREAD      19
#define ERR_FWRITE     20
#define ERR_FILEINFO   21
#define ERR_ASKCUT     22
#define ERR_ASKCOPY    23
#define ERR_ASKCLEAR   24
#define ERR_PRNOTRDY   25
#define ERR_NOSCRAP    26
#define ERR_MIDISHAREFULL 27
#define ERR_NOMIDISHARE 28
#define ERR_FILEFORMAT	29
#define ERR_NOEXTERN		30
#define ERR_STANDARD		31
#define ERR_NOTSAVED		32
#define ERR_SETCHANGE	33
#define ERR_FIMPORTOPEN	34
#define ERR_QUIT			35
#define ERR_MFOPEN      36
#define ERR_MFREAD      37
#define ERR_MFWRITE     38
#define ERR_NOBIG       39
#define ERR_NOGLOVE     40
